/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-28 at 17:35:41 UTC 
 * Modify at your own risk.
 */

package com.cloudid.useridendpoint;

/**
 * Service definition for Useridendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UseridendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Useridendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the useridendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://1-dot-sixth-oxygen-529.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "useridendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Useridendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Useridendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getUserID".
   *
   * This request holds the parameters needed by the the useridendpoint server.  After setting any
   * optional parameters, call the {@link GetUserID#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetUserID getUserID(java.lang.String id) throws java.io.IOException {
    GetUserID result = new GetUserID(id);
    initialize(result);
    return result;
  }

  public class GetUserID extends UseridendpointRequest<com.cloudid.useridendpoint.model.UserID> {

    private static final String REST_PATH = "userid/{id}";

    /**
     * Create a request for the method "getUserID".
     *
     * This request holds the parameters needed by the the useridendpoint server.  After setting any
     * optional parameters, call the {@link GetUserID#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetUserID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetUserID(java.lang.String id) {
      super(Useridendpoint.this, "GET", REST_PATH, null, com.cloudid.useridendpoint.model.UserID.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetUserID setAlt(java.lang.String alt) {
      return (GetUserID) super.setAlt(alt);
    }

    @Override
    public GetUserID setFields(java.lang.String fields) {
      return (GetUserID) super.setFields(fields);
    }

    @Override
    public GetUserID setKey(java.lang.String key) {
      return (GetUserID) super.setKey(key);
    }

    @Override
    public GetUserID setOauthToken(java.lang.String oauthToken) {
      return (GetUserID) super.setOauthToken(oauthToken);
    }

    @Override
    public GetUserID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetUserID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetUserID setQuotaUser(java.lang.String quotaUser) {
      return (GetUserID) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetUserID setUserIp(java.lang.String userIp) {
      return (GetUserID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetUserID setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetUserID set(String parameterName, Object value) {
      return (GetUserID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertUserID".
   *
   * This request holds the parameters needed by the the useridendpoint server.  After setting any
   * optional parameters, call the {@link InsertUserID#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.cloudid.useridendpoint.model.UserID}
   * @return the request
   */
  public InsertUserID insertUserID(com.cloudid.useridendpoint.model.UserID content) throws java.io.IOException {
    InsertUserID result = new InsertUserID(content);
    initialize(result);
    return result;
  }

  public class InsertUserID extends UseridendpointRequest<com.cloudid.useridendpoint.model.UserID> {

    private static final String REST_PATH = "userid";

    /**
     * Create a request for the method "insertUserID".
     *
     * This request holds the parameters needed by the the useridendpoint server.  After setting any
     * optional parameters, call the {@link InsertUserID#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertUserID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.cloudid.useridendpoint.model.UserID}
     * @since 1.13
     */
    protected InsertUserID(com.cloudid.useridendpoint.model.UserID content) {
      super(Useridendpoint.this, "POST", REST_PATH, content, com.cloudid.useridendpoint.model.UserID.class);
    }

    @Override
    public InsertUserID setAlt(java.lang.String alt) {
      return (InsertUserID) super.setAlt(alt);
    }

    @Override
    public InsertUserID setFields(java.lang.String fields) {
      return (InsertUserID) super.setFields(fields);
    }

    @Override
    public InsertUserID setKey(java.lang.String key) {
      return (InsertUserID) super.setKey(key);
    }

    @Override
    public InsertUserID setOauthToken(java.lang.String oauthToken) {
      return (InsertUserID) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertUserID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertUserID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertUserID setQuotaUser(java.lang.String quotaUser) {
      return (InsertUserID) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertUserID setUserIp(java.lang.String userIp) {
      return (InsertUserID) super.setUserIp(userIp);
    }

    @Override
    public InsertUserID set(String parameterName, Object value) {
      return (InsertUserID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listUserID".
   *
   * This request holds the parameters needed by the the useridendpoint server.  After setting any
   * optional parameters, call the {@link ListUserID#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListUserID listUserID() throws java.io.IOException {
    ListUserID result = new ListUserID();
    initialize(result);
    return result;
  }

  public class ListUserID extends UseridendpointRequest<com.cloudid.useridendpoint.model.CollectionResponseUserID> {

    private static final String REST_PATH = "userid";

    /**
     * Create a request for the method "listUserID".
     *
     * This request holds the parameters needed by the the useridendpoint server.  After setting any
     * optional parameters, call the {@link ListUserID#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListUserID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListUserID() {
      super(Useridendpoint.this, "GET", REST_PATH, null, com.cloudid.useridendpoint.model.CollectionResponseUserID.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListUserID setAlt(java.lang.String alt) {
      return (ListUserID) super.setAlt(alt);
    }

    @Override
    public ListUserID setFields(java.lang.String fields) {
      return (ListUserID) super.setFields(fields);
    }

    @Override
    public ListUserID setKey(java.lang.String key) {
      return (ListUserID) super.setKey(key);
    }

    @Override
    public ListUserID setOauthToken(java.lang.String oauthToken) {
      return (ListUserID) super.setOauthToken(oauthToken);
    }

    @Override
    public ListUserID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListUserID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListUserID setQuotaUser(java.lang.String quotaUser) {
      return (ListUserID) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListUserID setUserIp(java.lang.String userIp) {
      return (ListUserID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListUserID setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListUserID setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListUserID set(String parameterName, Object value) {
      return (ListUserID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeUserID".
   *
   * This request holds the parameters needed by the the useridendpoint server.  After setting any
   * optional parameters, call the {@link RemoveUserID#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveUserID removeUserID(java.lang.String id) throws java.io.IOException {
    RemoveUserID result = new RemoveUserID(id);
    initialize(result);
    return result;
  }

  public class RemoveUserID extends UseridendpointRequest<Void> {

    private static final String REST_PATH = "userid/{id}";

    /**
     * Create a request for the method "removeUserID".
     *
     * This request holds the parameters needed by the the useridendpoint server.  After setting any
     * optional parameters, call the {@link RemoveUserID#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveUserID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveUserID(java.lang.String id) {
      super(Useridendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveUserID setAlt(java.lang.String alt) {
      return (RemoveUserID) super.setAlt(alt);
    }

    @Override
    public RemoveUserID setFields(java.lang.String fields) {
      return (RemoveUserID) super.setFields(fields);
    }

    @Override
    public RemoveUserID setKey(java.lang.String key) {
      return (RemoveUserID) super.setKey(key);
    }

    @Override
    public RemoveUserID setOauthToken(java.lang.String oauthToken) {
      return (RemoveUserID) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveUserID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveUserID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveUserID setQuotaUser(java.lang.String quotaUser) {
      return (RemoveUserID) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveUserID setUserIp(java.lang.String userIp) {
      return (RemoveUserID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveUserID setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveUserID set(String parameterName, Object value) {
      return (RemoveUserID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateUserID".
   *
   * This request holds the parameters needed by the the useridendpoint server.  After setting any
   * optional parameters, call the {@link UpdateUserID#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.cloudid.useridendpoint.model.UserID}
   * @return the request
   */
  public UpdateUserID updateUserID(com.cloudid.useridendpoint.model.UserID content) throws java.io.IOException {
    UpdateUserID result = new UpdateUserID(content);
    initialize(result);
    return result;
  }

  public class UpdateUserID extends UseridendpointRequest<com.cloudid.useridendpoint.model.UserID> {

    private static final String REST_PATH = "userid";

    /**
     * Create a request for the method "updateUserID".
     *
     * This request holds the parameters needed by the the useridendpoint server.  After setting any
     * optional parameters, call the {@link UpdateUserID#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateUserID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.cloudid.useridendpoint.model.UserID}
     * @since 1.13
     */
    protected UpdateUserID(com.cloudid.useridendpoint.model.UserID content) {
      super(Useridendpoint.this, "PUT", REST_PATH, content, com.cloudid.useridendpoint.model.UserID.class);
    }

    @Override
    public UpdateUserID setAlt(java.lang.String alt) {
      return (UpdateUserID) super.setAlt(alt);
    }

    @Override
    public UpdateUserID setFields(java.lang.String fields) {
      return (UpdateUserID) super.setFields(fields);
    }

    @Override
    public UpdateUserID setKey(java.lang.String key) {
      return (UpdateUserID) super.setKey(key);
    }

    @Override
    public UpdateUserID setOauthToken(java.lang.String oauthToken) {
      return (UpdateUserID) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateUserID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateUserID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateUserID setQuotaUser(java.lang.String quotaUser) {
      return (UpdateUserID) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateUserID setUserIp(java.lang.String userIp) {
      return (UpdateUserID) super.setUserIp(userIp);
    }

    @Override
    public UpdateUserID set(String parameterName, Object value) {
      return (UpdateUserID) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Useridendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Useridendpoint}. */
    @Override
    public Useridendpoint build() {
      return new Useridendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UseridendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUseridendpointRequestInitializer(
        UseridendpointRequestInitializer useridendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(useridendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
