/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-28 at 17:35:26 UTC 
 * Modify at your own risk.
 */

package com.cloudid.useridinfoendpoint;

/**
 * Service definition for Useridinfoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UseridinfoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Useridinfoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the useridinfoendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://1-dot-sixth-oxygen-529.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "useridinfoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Useridinfoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Useridinfoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getUserIdInfo".
   *
   * This request holds the parameters needed by the the useridinfoendpoint server.  After setting any
   * optional parameters, call the {@link GetUserIdInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetUserIdInfo getUserIdInfo(java.lang.String id) throws java.io.IOException {
    GetUserIdInfo result = new GetUserIdInfo(id);
    initialize(result);
    return result;
  }

  public class GetUserIdInfo extends UseridinfoendpointRequest<com.cloudid.useridinfoendpoint.model.UserIdInfo> {

    private static final String REST_PATH = "useridinfo/{id}";

    /**
     * Create a request for the method "getUserIdInfo".
     *
     * This request holds the parameters needed by the the useridinfoendpoint server.  After setting
     * any optional parameters, call the {@link GetUserIdInfo#execute()} method to invoke the remote
     * operation. <p> {@link GetUserIdInfo#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetUserIdInfo(java.lang.String id) {
      super(Useridinfoendpoint.this, "GET", REST_PATH, null, com.cloudid.useridinfoendpoint.model.UserIdInfo.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetUserIdInfo setAlt(java.lang.String alt) {
      return (GetUserIdInfo) super.setAlt(alt);
    }

    @Override
    public GetUserIdInfo setFields(java.lang.String fields) {
      return (GetUserIdInfo) super.setFields(fields);
    }

    @Override
    public GetUserIdInfo setKey(java.lang.String key) {
      return (GetUserIdInfo) super.setKey(key);
    }

    @Override
    public GetUserIdInfo setOauthToken(java.lang.String oauthToken) {
      return (GetUserIdInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetUserIdInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetUserIdInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetUserIdInfo setQuotaUser(java.lang.String quotaUser) {
      return (GetUserIdInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetUserIdInfo setUserIp(java.lang.String userIp) {
      return (GetUserIdInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetUserIdInfo setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetUserIdInfo set(String parameterName, Object value) {
      return (GetUserIdInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertUserIdInfo".
   *
   * This request holds the parameters needed by the the useridinfoendpoint server.  After setting any
   * optional parameters, call the {@link InsertUserIdInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.cloudid.useridinfoendpoint.model.UserIdInfo}
   * @return the request
   */
  public InsertUserIdInfo insertUserIdInfo(com.cloudid.useridinfoendpoint.model.UserIdInfo content) throws java.io.IOException {
    InsertUserIdInfo result = new InsertUserIdInfo(content);
    initialize(result);
    return result;
  }

  public class InsertUserIdInfo extends UseridinfoendpointRequest<com.cloudid.useridinfoendpoint.model.UserIdInfo> {

    private static final String REST_PATH = "useridinfo";

    /**
     * Create a request for the method "insertUserIdInfo".
     *
     * This request holds the parameters needed by the the useridinfoendpoint server.  After setting
     * any optional parameters, call the {@link InsertUserIdInfo#execute()} method to invoke the
     * remote operation. <p> {@link InsertUserIdInfo#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.cloudid.useridinfoendpoint.model.UserIdInfo}
     * @since 1.13
     */
    protected InsertUserIdInfo(com.cloudid.useridinfoendpoint.model.UserIdInfo content) {
      super(Useridinfoendpoint.this, "POST", REST_PATH, content, com.cloudid.useridinfoendpoint.model.UserIdInfo.class);
    }

    @Override
    public InsertUserIdInfo setAlt(java.lang.String alt) {
      return (InsertUserIdInfo) super.setAlt(alt);
    }

    @Override
    public InsertUserIdInfo setFields(java.lang.String fields) {
      return (InsertUserIdInfo) super.setFields(fields);
    }

    @Override
    public InsertUserIdInfo setKey(java.lang.String key) {
      return (InsertUserIdInfo) super.setKey(key);
    }

    @Override
    public InsertUserIdInfo setOauthToken(java.lang.String oauthToken) {
      return (InsertUserIdInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertUserIdInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertUserIdInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertUserIdInfo setQuotaUser(java.lang.String quotaUser) {
      return (InsertUserIdInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertUserIdInfo setUserIp(java.lang.String userIp) {
      return (InsertUserIdInfo) super.setUserIp(userIp);
    }

    @Override
    public InsertUserIdInfo set(String parameterName, Object value) {
      return (InsertUserIdInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listUserIdInfo".
   *
   * This request holds the parameters needed by the the useridinfoendpoint server.  After setting any
   * optional parameters, call the {@link ListUserIdInfo#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListUserIdInfo listUserIdInfo() throws java.io.IOException {
    ListUserIdInfo result = new ListUserIdInfo();
    initialize(result);
    return result;
  }

  public class ListUserIdInfo extends UseridinfoendpointRequest<com.cloudid.useridinfoendpoint.model.CollectionResponseUserIdInfo> {

    private static final String REST_PATH = "useridinfo";

    /**
     * Create a request for the method "listUserIdInfo".
     *
     * This request holds the parameters needed by the the useridinfoendpoint server.  After setting
     * any optional parameters, call the {@link ListUserIdInfo#execute()} method to invoke the remote
     * operation. <p> {@link ListUserIdInfo#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListUserIdInfo() {
      super(Useridinfoendpoint.this, "GET", REST_PATH, null, com.cloudid.useridinfoendpoint.model.CollectionResponseUserIdInfo.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListUserIdInfo setAlt(java.lang.String alt) {
      return (ListUserIdInfo) super.setAlt(alt);
    }

    @Override
    public ListUserIdInfo setFields(java.lang.String fields) {
      return (ListUserIdInfo) super.setFields(fields);
    }

    @Override
    public ListUserIdInfo setKey(java.lang.String key) {
      return (ListUserIdInfo) super.setKey(key);
    }

    @Override
    public ListUserIdInfo setOauthToken(java.lang.String oauthToken) {
      return (ListUserIdInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public ListUserIdInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListUserIdInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListUserIdInfo setQuotaUser(java.lang.String quotaUser) {
      return (ListUserIdInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListUserIdInfo setUserIp(java.lang.String userIp) {
      return (ListUserIdInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListUserIdInfo setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListUserIdInfo setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListUserIdInfo set(String parameterName, Object value) {
      return (ListUserIdInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeUserIdInfo".
   *
   * This request holds the parameters needed by the the useridinfoendpoint server.  After setting any
   * optional parameters, call the {@link RemoveUserIdInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveUserIdInfo removeUserIdInfo(java.lang.String id) throws java.io.IOException {
    RemoveUserIdInfo result = new RemoveUserIdInfo(id);
    initialize(result);
    return result;
  }

  public class RemoveUserIdInfo extends UseridinfoendpointRequest<Void> {

    private static final String REST_PATH = "useridinfo/{id}";

    /**
     * Create a request for the method "removeUserIdInfo".
     *
     * This request holds the parameters needed by the the useridinfoendpoint server.  After setting
     * any optional parameters, call the {@link RemoveUserIdInfo#execute()} method to invoke the
     * remote operation. <p> {@link RemoveUserIdInfo#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveUserIdInfo(java.lang.String id) {
      super(Useridinfoendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveUserIdInfo setAlt(java.lang.String alt) {
      return (RemoveUserIdInfo) super.setAlt(alt);
    }

    @Override
    public RemoveUserIdInfo setFields(java.lang.String fields) {
      return (RemoveUserIdInfo) super.setFields(fields);
    }

    @Override
    public RemoveUserIdInfo setKey(java.lang.String key) {
      return (RemoveUserIdInfo) super.setKey(key);
    }

    @Override
    public RemoveUserIdInfo setOauthToken(java.lang.String oauthToken) {
      return (RemoveUserIdInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveUserIdInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveUserIdInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveUserIdInfo setQuotaUser(java.lang.String quotaUser) {
      return (RemoveUserIdInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveUserIdInfo setUserIp(java.lang.String userIp) {
      return (RemoveUserIdInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveUserIdInfo setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveUserIdInfo set(String parameterName, Object value) {
      return (RemoveUserIdInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateUserIdInfo".
   *
   * This request holds the parameters needed by the the useridinfoendpoint server.  After setting any
   * optional parameters, call the {@link UpdateUserIdInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.cloudid.useridinfoendpoint.model.UserIdInfo}
   * @return the request
   */
  public UpdateUserIdInfo updateUserIdInfo(com.cloudid.useridinfoendpoint.model.UserIdInfo content) throws java.io.IOException {
    UpdateUserIdInfo result = new UpdateUserIdInfo(content);
    initialize(result);
    return result;
  }

  public class UpdateUserIdInfo extends UseridinfoendpointRequest<com.cloudid.useridinfoendpoint.model.UserIdInfo> {

    private static final String REST_PATH = "useridinfo";

    /**
     * Create a request for the method "updateUserIdInfo".
     *
     * This request holds the parameters needed by the the useridinfoendpoint server.  After setting
     * any optional parameters, call the {@link UpdateUserIdInfo#execute()} method to invoke the
     * remote operation. <p> {@link UpdateUserIdInfo#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.cloudid.useridinfoendpoint.model.UserIdInfo}
     * @since 1.13
     */
    protected UpdateUserIdInfo(com.cloudid.useridinfoendpoint.model.UserIdInfo content) {
      super(Useridinfoendpoint.this, "PUT", REST_PATH, content, com.cloudid.useridinfoendpoint.model.UserIdInfo.class);
    }

    @Override
    public UpdateUserIdInfo setAlt(java.lang.String alt) {
      return (UpdateUserIdInfo) super.setAlt(alt);
    }

    @Override
    public UpdateUserIdInfo setFields(java.lang.String fields) {
      return (UpdateUserIdInfo) super.setFields(fields);
    }

    @Override
    public UpdateUserIdInfo setKey(java.lang.String key) {
      return (UpdateUserIdInfo) super.setKey(key);
    }

    @Override
    public UpdateUserIdInfo setOauthToken(java.lang.String oauthToken) {
      return (UpdateUserIdInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateUserIdInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateUserIdInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateUserIdInfo setQuotaUser(java.lang.String quotaUser) {
      return (UpdateUserIdInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateUserIdInfo setUserIp(java.lang.String userIp) {
      return (UpdateUserIdInfo) super.setUserIp(userIp);
    }

    @Override
    public UpdateUserIdInfo set(String parameterName, Object value) {
      return (UpdateUserIdInfo) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Useridinfoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Useridinfoendpoint}. */
    @Override
    public Useridinfoendpoint build() {
      return new Useridinfoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UseridinfoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUseridinfoendpointRequestInitializer(
        UseridinfoendpointRequestInitializer useridinfoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(useridinfoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
